<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>To Do App</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="../styles.css">
</head>
<body>
<h1>To Do App</h1>
<section class="mainSection">
<?php
echo '<form method="post" id="newTask">
    <label>Edit Task: </label>
    <input type="text" name="newTask" placeholder="' . $task['task'] . '">
    <input type="submit" value="Edit">
</form>';
?>
<a class="link" href="/completedTasks">Show completed tasks</a>
<a class="link" href="/">Home</a>
</section>
</body>
</html>
