<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>To Do App</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="../styles.css"
    <style>


    </style>
</head>
<body>
<h1>To Do App</h1>

<section class="mainSection">
<form method="post" id="newTask">
    <label>Add Task: </label>
    <input type="text" name="newTask">
    <input type="submit">
</form>

<?php
foreach ($tasks as $task){
    echo '<div class="buttonDiv">
              <h4>' . $task['task'] . '</h4>
              <div>
                <a class="button" href="/markComplete/'. $task['id']. '">✅</a>
                <a class="button" href="/edit/'.$task['id'].'">✎</a>
              </div>
          </div>';
}
?>
<a class="link" href="/completedTasks">Show completed tasks</a>
</section>
</body>
</html>
